import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#020617',
        padding: 20,
    },
    glassCard: {
        backgroundColor: 'rgba(15, 23, 42, 0.7)',
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 10,
    },
    title: {
        fontSize: 28,
        fontWeight: '900',
        color: '#f8fafc',
        textAlign: 'center',
        marginBottom: 10,
        letterSpacing: -1,
    },
    input: {
        backgroundColor: 'rgba(2, 6, 23, 0.6)',
        borderRadius: 14,
        padding: 14,
        color: '#fff',
        marginBottom: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        fontSize: 16,
    },
    button: {
        backgroundColor: '#8b5cf6',
        borderRadius: 14,
        padding: 16,
        alignItems: 'center',
        shadowColor: '#8b5cf6',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        textAlign: 'center',
    },
    msgUser: {
        alignSelf: 'flex-end',
        backgroundColor: '#8b5cf6',
        padding: 14,
        borderRadius: 20,
        borderBottomRightRadius: 4,
        marginVertical: 6,
        maxWidth: '82%',
        shadowColor: '#8b5cf6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    msgBot: {
        alignSelf: 'flex-start',
        backgroundColor: 'rgba(255,255,255,0.03)',
        padding: 14,
        borderRadius: 20,
        borderBottomLeftRadius: 4,
        marginVertical: 6,
        maxWidth: '85%',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    text: {
        color: '#f8fafc',
        fontSize: 16,
        lineHeight: 22,
    }
});
